/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-04-13 07:31:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\" />\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"logo.png\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/vnd.microsoft.icon\" href=\"favicon.ico\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"favicon.png\">\r\n");
      out.write("<title>Red5 - OFLADemo</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("    background-color:#680000;\r\n");
      out.write("    font-family: sans-serif;\r\n");
      out.write("    font-size: 0.9em;\r\n");
      out.write("}\r\n");
      out.write(".code {\r\n");
      out.write("    font-family: monospace;\r\n");
      out.write("    font-size: 130%;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("    color: red;\r\n");
      out.write("    background: white;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("#information {\r\n");
      out.write("    padding-top: 1em;\r\n");
      out.write("    padding-bottom: 1em;\r\n");
      out.write("}\r\n");
      out.write(".spiffy{display:block}\r\n");
      out.write(".spiffy *{\r\n");
      out.write("  display:block;\r\n");
      out.write("  height:1px;\r\n");
      out.write("  overflow:hidden;\r\n");
      out.write("  font-size:.01em;\r\n");
      out.write("  background:#fff}\r\n");
      out.write(".spiffy1{\r\n");
      out.write("  margin-left:3px;\r\n");
      out.write("  margin-right:3px;\r\n");
      out.write("  padding-left:1px;\r\n");
      out.write("  padding-right:1px;\r\n");
      out.write("  border-left:1px solid #b60600;\r\n");
      out.write("  border-right:1px solid #b60600;\r\n");
      out.write("  background:#df0b00}\r\n");
      out.write(".spiffy2{\r\n");
      out.write("  margin-left:1px;\r\n");
      out.write("  margin-right:1px;\r\n");
      out.write("  padding-right:1px;\r\n");
      out.write("  padding-left:1px;\r\n");
      out.write("  border-left:1px solid #8c0100;\r\n");
      out.write("  border-right:1px solid #8c0100;\r\n");
      out.write("  background:#e60c00}\r\n");
      out.write(".spiffy3{\r\n");
      out.write("  margin-left:1px;\r\n");
      out.write("  margin-right:1px;\r\n");
      out.write("  border-left:1px solid #e60c00;\r\n");
      out.write("  border-right:1px solid #e60c00;}\r\n");
      out.write(".spiffy4{\r\n");
      out.write("  border-left:1px solid #b60600;\r\n");
      out.write("  border-right:1px solid #b60600}\r\n");
      out.write(".spiffy5{\r\n");
      out.write("  border-left:1px solid #df0b00;\r\n");
      out.write("  border-right:1px solid #df0b00}\r\n");
      out.write(".spiffyfg{\r\n");
      out.write("    padding:1em;\r\n");
      out.write("    background-color:#fff;\r\n");
      out.write("}\r\n");
      out.write("  -->\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script type='text/javascript' src='");
      out.print(request.getContextPath() );
      out.write("/resources/red5/jwplayer.js'></script>\r\n");
      out.write("<div>\r\n");
      out.write("  <b class=\"spiffy\">\r\n");
      out.write("  <b class=\"spiffy1\"><b></b></b>\r\n");
      out.write("  <b class=\"spiffy2\"><b></b></b>\r\n");
      out.write("  <b class=\"spiffy3\"></b>\r\n");
      out.write("  <b class=\"spiffy4\"></b>\r\n");
      out.write("  <b class=\"spiffy5\"></b></b>\r\n");
      out.write("  \r\n");
      out.write("<div class=\"spiffyfg\">\r\n");
      out.write("\r\n");
      out.write("<p>This page demonstrates the use of <a href=\"http://www.longtailvideo.com/jw-player/\" target=\"_blank\">JWPlayer</a> to stream media from the OFLADemo application. If you want the classic version, click <a href=\"/demos/ofla_demo.html\">here</a></p>\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("<b>RTMP</b>\r\n");
      out.write("<div id='mediaspace'>This text will be replaced</div>\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("  jwplayer('mediaspace').setup({\r\n");
      out.write("    'flashplayer': '");
      out.print(request.getContextPath() );
      out.write("/resources/red5/player.swf',\r\n");
      out.write("    'file': 'Avengers2.mp4',\r\n");
      out.write("    'streamer': 'rtmp://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${www}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/default',\r\n");
      out.write("    'controlbar': 'bottom',\r\n");
      out.write("    'width': '848',\r\n");
      out.write("    'height': '360'\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("<br />\r\n");
      out.write("\r\n");
      out.write("<b>RTMPT</b>\r\n");
      out.write("<div id='mediaspace2'>This text will be replaced</div>\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("  jwplayer('mediaspace2').setup({\r\n");
      out.write("    'flashplayer': '");
      out.print(request.getContextPath() );
      out.write("/resources/red5/player.swf',\r\n");
      out.write("    'file': 'Avengers2.mp4',\r\n");
      out.write("    'streamer': 'rtmpt://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${www}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(":5080/video',\r\n");
      out.write("    'controlbar': 'bottom',\r\n");
      out.write("    'width': '848',\r\n");
      out.write("    'height': '360'\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("<br />\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  <b class=\"spiffy\">\r\n");
      out.write("  <b class=\"spiffy5\"></b>\r\n");
      out.write("  <b class=\"spiffy4\"></b>\r\n");
      out.write("  <b class=\"spiffy3\"></b>\r\n");
      out.write("  <b class=\"spiffy2\"><b></b></b>\r\n");
      out.write("  <b class=\"spiffy1\"><b></b></b></b>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
